apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    run: nodeapp
  template:
    spec:
      containers:
      - image: gcr.io/practise-317714/helloworld:32066d133d4a4ff1e830f423264c5e069127fdcf
        name: helloworld
  type: LoadBalancer
